# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a49a765b19729e6bb77992238156c225d3ba3bd4f95c68ea6966cc25b02d921c3fdfc734090b39d90043470c79f0e12cd23ebb87e3aa2665f8e4cf90f640fc

test:
  secret_key_base: 301ebcde9c09061b4124b09364fccabc43d8cdfbf641cfa0fed816a50a532c209d6fa94df3029123f989297043290aa179964c10b7142a111eef83bca7f48b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
